### ISSUE TITLE
Does configmapcontroller needs to be installed?

### ISSUE THREAD

**Issue by elzinko** [fabric8io/configmapcontroller#12]
Hi!
I'm trying to use configmapcontroller to update my pod when a configmap is updated. I tried with a spring-boot application. Can I use it with openshift? Do I have to install something? where?
Thx for help.

**Comment by kameshsampath** [comment]
yes @elzinko , it can be used and works with openshift as well. it might require you add the view role to the project default service account to access the configmaps from the namespace, it cane be done using the following command `oc policy add-role-to-user view system:serviceaccount:$(oc project -q):default -n $(oc project -q)`

**Comment by elzinko** [comment]
Thanks for your response. I just realized that configmapcontoller was automatically installed by fabric8. I was trying to use it only with the fabric8 maven plugin without the fabric8 stack. Sorry for the misunderstood
